# Generated by Django 4.2.1 on 2023-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='blog_posts',
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
